USE music
GO
INSERT INTO Album VALUES ('pnd1','Pendulum','Hold Your Colour','2005-07-25');
INSERT INTO Album VALUES ('pnd2','Pendulum','In Silico','2008-05-12');
INSERT INTO Album VALUES ('pnd3','Pendulum','Immersion','2010-05-24');
INSERT INTO Tracks VALUES ('Prelude','0:52','pnd1','null');
INSERT INTO Tracks VALUES ('Slam','5:44','pnd1','gIOQfdn9L9c');
INSERT INTO Tracks VALUES ('Plasticworld','6:21','pnd1','null');
INSERT INTO Tracks VALUES ('Fasten Your Seatbelt','6:38','pnd1','null');
INSERT INTO Tracks VALUES ('Through the Loop','6:13','pnd1','null');
INSERT INTO Tracks VALUES ('Sounds of Life','5:21','pnd1','null');
INSERT INTO Tracks VALUES ('Girl in the Fire','4:53','pnd1','null');
INSERT INTO Tracks VALUES ('Tarantula','5:31','pnd1','null');
INSERT INTO Tracks VALUES ('Out Here','6:07','pnd1','null');
INSERT INTO Tracks VALUES ('Hold Your Colour','5:28','pnd1','null');
INSERT INTO Tracks VALUES ('The Terminal','5:42','pnd1','null');
INSERT INTO Tracks VALUES ('Streamline','5:23','pnd1','null');
INSERT INTO Tracks VALUES ('Another Planet','7:38','pnd1','null');
INSERT INTO Tracks VALUES ('Still Grey','7:51','pnd1','null');
INSERT INTO Tracks VALUES ('Showdown','5:27','pnd2','X6BKBIOtRXw');
INSERT INTO Tracks VALUES ('Different','5:51','pnd2','null');
INSERT INTO Tracks VALUES ('Propane Nightmares','5:13','pnd2','WPbeEtjo70g');
INSERT INTO Tracks VALUES ('Visions','5:36','pnd2','null');
INSERT INTO Tracks VALUES ('Midnight Runner','6:55','pnd2','null');
INSERT INTO Tracks VALUES ('The Other Side','5:15','pnd2','zENtEumtyBI');
INSERT INTO Tracks VALUES ('Mutiny','5:09','pnd2','null');
INSERT INTO Tracks VALUES ('9,000 Miles','6:26','pnd2','null');
INSERT INTO Tracks VALUES ('Granite','4:41','pnd2','DQA1d0QQvf8');
INSERT INTO Tracks VALUES ('The Tempest','7:27','pnd2','null');
INSERT INTO Tracks VALUES ('Genesis','1:09','pnd3','null');
INSERT INTO Tracks VALUES ('Salt in the Wounds','6:38','pnd3','null');
INSERT INTO Tracks VALUES ('Watercolour','5:04','pnd3','tEPB7uzKuh4');
INSERT INTO Tracks VALUES ('Set Me on Fire','5:02','pnd3','null');
INSERT INTO Tracks VALUES ('Crush','4:13','pnd3','8mYd2X_9rrs');
INSERT INTO Tracks VALUES ('Under the Waves','4:54','pnd3','null');
INSERT INTO Tracks VALUES ('Immunize','4:36','pnd3','null');
INSERT INTO Tracks VALUES ('The Island – Pt.I (Dawn)','5:20','pnd3','hszZmFRPqx8');
INSERT INTO Tracks VALUES ('The Island – Pt.II (Dusk)','4:09','pnd3','null');
INSERT INTO Tracks VALUES ('Comprachicos','2:48','pnd3','null');
INSERT INTO Tracks VALUES ('The Vulture','4:03','pnd3','null');
INSERT INTO Tracks VALUES ('Witchcraft','4:12','pnd3','ogMNV33AhCY');
INSERT INTO Tracks VALUES ('Self vs. Self','4:45','pnd3','null');
INSERT INTO Tracks VALUES ('The Fountain','5:00','pnd3','null');
INSERT INTO Tracks VALUES ('Encoder','5:21','pnd3','null');
USE music
go
INSERT INTO Album VALUES ('emp1','Hollywood Undead','Empie','2020-02-14');
INSERT INTO Album VALUES ('fv55','Hollywood Undead','Five','2017-10-17');
INSERT INTO Album VALUES ('dotd','Hollywood Undead','Day of the dead','2015-03-31');
INSERT INTO Album VALUES ('at22','Hollywood Undead','American Tragedy','2011-04-05');
INSERT INTO Tracks VALUES ('Time Bomb','3:37','emp1','null');
INSERT INTO Tracks VALUES ('Heart of a Champion','emp1','3:30','null');
INSERT INTO Tracks VALUES ('Empire','3:59','emp1','null');
INSERT INTO Tracks VALUES ('Enemy','3:11','emp1','null');
INSERT INTO Tracks VALUES ('Nightmare','3:40','emp1','null');
INSERT INTO Tracks VALUES ('Second Chances','4:13','emp1','null');
INSERT INTO Tracks VALUES ('California Dreaming','3:54','fv55','jjjaU5kQV8k');
INSERT INTO Tracks VALUES ('Whatever It Takes','3:54','fv55','teRTjJUc6vo');
INSERT INTO Tracks VALUES ('Bad Moon','3:07','fv55','null');
INSERT INTO Tracks VALUES ('Ghost Beach','3:07','fv55','null');
INSERT INTO Tracks VALUES ('Broken Record','3:58','fv55','null');
INSERT INTO Tracks VALUES ('Nobodys Watching','3:39','fv55','null');
INSERT INTO Tracks VALUES ('Cashed Out','3:47','fv55','null');
INSERT INTO Tracks VALUES ('Usual Suspects','3:44','dotd','6wsm5y07qDs');
INSERT INTO Tracks VALUES ('How We Roll','4:45','dotd','null');
INSERT INTO Tracks VALUES ('Day of the Dead','3:55','dotd','bl0e5DrYLyY');
INSERT INTO Tracks VALUES ('Take Me Home','4:39','dotd','null');
INSERT INTO Tracks VALUES ('Gravity','3:19','dotd','yjREC9hg6bU');
INSERT INTO Tracks VALUES ('Been to Hell','3:23','at22','SFnE2_DUhbs');
INSERT INTO Tracks VALUES ('Apologize','3:27','at22','null');
INSERT INTO Tracks VALUES ('Comin in Hot','3:43','at22','TP5cjnVGJ38');
INSERT INTO Tracks VALUES ('I Dont Wanna Die','3:59','at22','null');
INSERT INTO Tracks VALUES ('Hear Me Now','3:34','at22','pdoIs1jZbCY');
INSERT INTO Tracks VALUES ('Lights Out','3:51','at22','null');
